language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
install:
  - pwd
  - ls
  - bash -c 'if [ ! -e "generated" ]; then mkdir "generated"; fi;'
  - bash -c 'if [ ! -e "runtime" ]; then mkdir "runtime"; fi;'
  - chmod 777 generated
  - chmod 777 runtime
  # Remove possible obsolete tests
  - bash -c 'if [ -e "vendor/maslosoft/sprite-test" ]; then rm -rf "vendor/maslosoft/sprite-test"; fi;'
  # Required for PHP 5
  - composer update
  - composer install --prefer-dist --dev --no-interaction
before_script:
  - cd $TRAVIS_BUILD_DIR
script: 
  - bash run-travis
